# Generated by Django 6.0.1 on 2026-02-02 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('arme', 'Arme'), ('défense', 'Défense')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chevalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chevalier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChevalierEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chevalier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chevalier')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipement')),
            ],
            options={
                'unique_together': {('chevalier', 'equipement')},
            },
        ),
        migrations.AddField(
            model_name='chevalier',
            name='equipement',
            field=models.ManyToManyField(through='api.ChevalierEquipement', to='api.equipement'),
        ),
    ]
